title: Md Ariful Amin
logo: images.jpg
description: Data Science & Machine Learning Enthusiast | Software Engineer
show_downloads: false
theme: jekyll-theme-minimal

# Custom HTML for Social Links
social_html: |
  <p><strong>ğŸ“ Contact Number:</strong> <a href="tel:+46-722705966">+46-722705966</a></p>
  <p><strong>ğŸ”— LinkedIn:</strong> <a href="https://www.linkedin.com/in/ariful-amin/" target="_blank">My LinkedIn</a></p>
  <p><strong>âœ‰ï¸ Email:</strong> <a href="mailto:arifulamindu@gmail.com">arifulamindu@gmail.com</a></p>
  <p><strong>ğŸ“ Location:</strong> MalmÃ¶, Sweden</p>

