title: Md Ariful Amin
logo: images.jpg
description: Data Science & Machine Learning Enthusiast | Software Engineer
ğŸ“ +46-722705966  
ğŸ”— [LinkedIn](https://www.linkedin.com/in/ariful-amin/)
âœ‰ï¸ arifulamindu@gmail.com  
ğŸ“ MalmÃ¶, Sweden  
show_downloads: False
theme: jekyll-theme-minimal
